server.port: 19001

# tomcat最大线程数，默认为200
server.tomcat.max-threads: 800

# 主数据源，默认的
spring.datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql.vortex.com/cloud_management_prod?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
  username: root
  password: vortex
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒 
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小 
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
  filters: stat,wall,log4j
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  # useGlobalDataSourceStat: true


# 第二数据源
spring.datasource2: 
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql.vortex.com/cloud_management_prod?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
  username: root
  password: vortex
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒 
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小 
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
  filters: stat,wall,log4j
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  # useGlobalDataSourceStat: true

#hibernate
hibernate: 
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl.auto: update
  show_sql: false
  format_sql: false
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  packagesToScan: com.vortex.cloud



spring.redis:
  database: 3
  host: localhost
  port: 6379
  password: 123456
  timeout: 0
  pool:
    max-active: -1
    max-wait: -1
    max-idle: 8
    min-idle: 0

URL_GATEWAY: http://localhost:8080

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      
server.kafka.address: 114.55.237.39:9092